# Generated by Django 2.2 on 2019-04-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('NA', 'NA'), ('SEA', 'SEA'), ('EUR', 'Europe'), ('ASIA', 'ASIA'), ('CHINA', 'CHINA')], max_length=50)),
                ('city_ID', models.IntegerField()),
                ('product_ID', models.CharField(default='', max_length=50)),
                ('target', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Amazon',
            fields=[
                ('company', models.CharField(default='Amazon', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.BaseClass')),
            ],
        ),
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('company', models.CharField(default='Apple', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.BaseClass')),
            ],
            bases=('QA.baseclass',),
        ),
        migrations.CreateModel(
            name='Hp',
            fields=[
                ('company', models.CharField(default='Hp', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.BaseClass')),
            ],
            bases=('QA.baseclass',),
        ),
        migrations.CreateModel(
            name='Intel',
            fields=[
                ('company', models.CharField(default='Intel', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.BaseClass')),
            ],
            bases=('QA.baseclass',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('company', models.CharField(default='Samsung', max_length=50)),
                ('information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='QA.BaseClass')),
            ],
            bases=('QA.baseclass',),
        ),
    ]
